public with sharing class AccountTriggerHelper {
    public static Boolean hasRun = false;

    public void doTask1() {
        System.debug('doTask1');
    }

    public void doTask2() {
        System.debug('doTask2');
    }

    public void doTask3() {
        System.debug('doTask3');
    }

    public void doTask4() {
        System.debug('doTask4');
    }

    public void doTask5() {
        System.debug('doTask5');
    }

    public void doTask6() {
        System.debug('doTask6');
    }

    public void doTask7() {
        System.debug('doTask7');
    }
}